### Get list from server
GET http://localhost:8000/api/v1/tasks

### Postlist from server
POST http://localhost:8000/api/v1/tasks
//header of the request
Content-Type: application/json

//body of the request, there should be gap between header and body
{
"task": "Coding",
"hr": 40,
"type" : "entry"
}

### Update data
PATCH http://localhost:8000/api/v1/tasks
//header of the request
Content-Type: application/json

//body of the request, there should be gap between header and body
{
 "type": "bad",
      "id": "uzWAzt"
}

### delete data
DELETE  http://localhost:8000/api/v1/tasks
//header of the request
Content-Type: application/json

//body of the request, there should be gap between header and body
{
 
      "id": "JrXKPU"
}